name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, curl, zip, sqlite3, gd

    - name: Install dependencies
      run: composer install --no-interaction --prefer-dist --no-progress

    - name: Run PHPCS
      run: vendor/bin/phpcs --standard=PSR12 lib/

    - name: Run PHPMD
      run: vendor/bin/phpmd lib/ text cleancode,codesize,unusedcode

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse lib/ --level=10

    - name: Create coverage directory
      run: mkdir -p coverage

    - name: Run PHPUnit
      run: vendor/bin/phpunit --coverage-cobertura ./coverage/coverage.cobertura.xml

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
        
    - name: Add Code Coverage to GitHub Summary
      run: |
          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      if: success()

